-- table: messages, columns: sender_id int4, recipient_id, content, created_at, updated_at

CREATE TABLE public.messages (
  id integer generated by default as identity primary key,
  recipient_id integer NOT NULL REFERENCES public.person(id),
  sender_id integer NOT NULL REFERENCES public.person(id),
  content text NOT NULL,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


