--allow rewriting of tables if you make changes.
DROP TABLE if exists public.medical_visit;
DROP TABLE if exists public.appointment_booking;
DROP TABLE if exists public.patient;
DROP TABLE if exists public.address;
DROP TABLE if exists public.contact;
DROP TABLE if exists public.person;

DROP TYPE if exists public.contact_type;
DROP TYPE if exists public.user_role;
---

CREATE TYPE public.user_role AS ENUM (
    'patient',
    'admin',
    'provider'
);

CREATE TYPE public.contact_type AS ENUM (
  'phone',
  'email'
);

CREATE TABLE public.person (
  id integer generated by default as identity primary key,
  first_name varchar(255),
  last_name varchar(255),
  role public.user_role,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


CREATE TABLE public.contact (
  id integer generated by default as identity primary key,
  person_id integer,
  contact_type public.contact_type, -- phone || email 
  contact_value varchar(50),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  CONSTRAINT fk_contact_person
  FOREIGN KEY(person_id)
  REFERENCES person(id)
  ON DELETE CASCADE
);

CREATE TABLE public.address (
  id integer generated by default as identity primary key,
  person_id integer,
  streetA varchar(255),
  streetB varchar(255),
  city varchar(255),
  address_state varchar(25),
  zip_code varchar(10),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

  CONSTRAINT fk_address_person
  FOREIGN KEY(person_id)
  REFERENCES person(id)
  ON DELETE CASCADE
);

CREATE TABLE public.patient(
  id integer generated by default as identity primary key,
  person_id integer UNIQUE,
  date_of_birth date,
  sex varchar(10),
  insurance_flag boolean,
  emergency_contact json,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),

CONSTRAINT fk_patient_person
FOREIGN KEY(person_id)
REFERENCES person(id)
ON DELETE CASCADE
);

CREATE TABLE public.appointment_booking(
  id integer generated by default as identity primary key,
  person_id integer,
  date_of_birth date,
  date_paid date,
  sex varchar(10),
  insurance_flag boolean,
  emergency_contact json,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  
CONSTRAINT fk_appointment_patient
FOREIGN KEY(person_id)
REFERENCES person(id)
ON DELETE CASCADE
);

CREATE TABLE public.medical_visit(
  id integer generated by default as identity primary key,
  patient_id integer,
  doctor_id integer,
  allergies varchar[],
  prescriptions varchar[],
  summary_notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  followup_needed date,

CONSTRAINT fk_visit_patient
FOREIGN KEY(patient_id)
REFERENCES patient(id)
ON DELETE CASCADE,

CONSTRAINT fk_visit_doctor
FOREIGN KEY(doctor_id)
REFERENCES public.person(id) -- is this correct? was confused about the provider role
ON DELETE CASCADE
);


-- --allow rewriting of tables part 2
-- alter table public.person
-- -- enable row level security;

-- alter table public.telecom
-- -- enable row level security;

-- alter table public.address
-- -- enable row level security;

-- alter table public.patient
-- -- enable row level security;

-- alter table public.appointment
-- -- enable row level security;

-- alter table public.medical_visit
-- -- enable row level security;
--
