ALTER TABLE public.address DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.person DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.medical_visit DISABLE ROW LEVEL SECURITY;